Repository onepanelio/onepanel, pull requests merged in 2020-11, with the labels that each got.

#702 fix: issue where terminated workspace labels were being selected
  pkg/labels.go
Labels: area/core, kind/bug

#709 fix: issue where new migration ran before all others, causing issues
  db/go/20201102104048_update_cvat_reduce_vols.go
  db/go/db.go
Labels: area/core, kind/bug

#711 fix: Only inject one sys-send-status task
  pkg/workflow_execution.go
Labels: kind/bug

#736 feat: add metrics database support to workflow executions
  api/api.swagger.json
  api/workflow.pb.go
  api/workflow.proto
  db/sql/20201116105825_add_metrics_to_workflows.sql
  go.sum
  pkg/types.go
  pkg/types_test.go
  pkg/workflow_execution.go
  pkg/workflow_execution_types.go
  server/converter/converter.go
  server/workflow_server.go
Labels: area/core

#740 build: Bring Go to 1.15.5 in Dockerfile
  Dockerfile
Labels: kind/enhancement

#729 feat: include LF AI Landscape onepanel link
  README.md
Labels: area/docs

#744 fix: github actions
  .github/workflows/push_tag.yaml
Labels: area/core
