Repository onepanelio/onepanel, pull requests merged in 2020-06, with the labels that each got.

#310 feat: workflow template created at is selected when listing workflow executions
  pkg/workflow_execution.go
Labels: kind/enhancement

#312 chore: generate release MD script
  scripts/README.md
  scripts/generate-release-md.go
Labels: kind/docs

#286 feat: add cvat migration template
  Dockerfile
  cmd/goose.go
  db/20200525160514_add_jupyter_workspace_template.go
  db/20200528140124_add_cvat_workspace_template.go
  pkg/workspace.go
  pkg/workspace_template.go
Labels: kind/enhancement

#326 fix: Slack notify YAML indentation
  db/20200525160514_add_jupyter_workspace_template.go
  db/20200528140124_add_cvat_workspace_template.go
Labels: kind/bug
